language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install coveralls pytest-cov pytest
  - pip install bokeh pandas
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov bandwagon --cov-report term-missing

after_success:
  - coveralls
