language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install pytest
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -e .
# command to run tests
script:
  - python -m pytest
